import { Toaster } from '@/components/ui/sonner'
import type { Metadata } from 'next'
import { Noto_Sans, Noto_Sans_Devanagari } from 'next/font/google'
import './globals.css'

const notoSans = Noto_Sans({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const notoSansDevanagari = Noto_Sans_Devanagari({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html
            lang='en'
            className='dark'>
            <body className={`${notoSans.variable} ${notoSansDevanagari.variable} antialiased`}>
                <main className='h-screen w-screen flex flex-col'>{children}</main>
                <Toaster />
            </body>
        </html>
    )
}
